// Optimize sourced venue photos into web-ready WebP + generate blur placeholders.
// Run: npm run optimize:images
import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
import { join, parse } from "node:path";

const SRC = "assets/sourced";
const OUT_DIRS = ["assets/img", "public/img"];
const BLUR_TS = "src/lib/blur.ts";

// Wider output for hero / featured cocktails + full-bleed atmosphere shots.
const WIDE = new Set([
  "blood-on-the-leaves-hero",
  "negroni-hi",
  "oasis-spirit-hi",
  // Atmosphere / the room — used large in gallery, about and home.
  "room-stories",
  "quiet-corner",
  "evenings-stretch",
  "whimsical-charm",
  "heart-of-city",
  "bygone-era",
  "warm-sunshine",
  "coziness",
  "candlelight",
]);

await Promise.all(OUT_DIRS.map((d) => mkdir(d, { recursive: true })));

const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f));
const blur = {};

for (const file of files) {
  const { name } = parse(file);
  const input = join(SRC, file);
  const width = WIDE.has(name) ? 1600 : 1000;

  const pipeline = sharp(input)
    .rotate()
    .resize({ width, withoutEnlargement: true });

  const webp = await pipeline
    .clone()
    .webp({ quality: 82, effort: 5 })
    .toBuffer();

  for (const dir of OUT_DIRS) {
    await writeFile(join(dir, `${name}.webp`), webp);
  }

  // Low-quality image placeholder (tiny blurred base64) for next/image blurDataURL.
  const lqip = await sharp(input)
    .resize({ width: 20 })
    .webp({ quality: 30 })
    .toBuffer();
  blur[name] = `data:image/webp;base64,${lqip.toString("base64")}`;

  console.log(`✓ ${name}.webp  (${(webp.length / 1024).toFixed(0)}KB, ${width}px)`);
}

const ts = `// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export const blurData: Record<string, string> = ${JSON.stringify(blur, null, 2)};
`;
await mkdir("src/lib", { recursive: true });
await writeFile(BLUR_TS, ts);
console.log(`✓ wrote ${files.length} images to ${OUT_DIRS.join(", ")} + blur map`);
